project_id = "fkitunwtvwgmcyqfrdjo"

[auth]
enabled = true
site_url = "http://localhost:5173"

[functions.analyze-cv]
verify_jwt = false

[functions.analyze-cv-with-ai]
verify_jwt = false

[functions.receive-cv-analysis]
verify_jwt = false

[functions.receive-questions]
verify_jwt = false

[functions.send-to-n8n]
verify_jwt = false

[functions.send-assessments]
verify_jwt = false
